<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gender_sex</name>
   <tag></tag>
   <elementGuidId>c31e381f-a71d-4054-89e4-e3b92609fc52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sex-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sex-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>740ee8d9-650c-4046-8c2d-79291543329c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sex-0</value>
      <webElementGuid>b7def064-d463-438e-866d-0cc54f0a551c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sex</value>
      <webElementGuid>7673b3ff-1e56-4330-86d0-c381053661cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4744f4f0-e4a8-43ca-8f99-52fb6e558df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>f7d563f6-d71c-4253-a960-f95cd9a80c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sex-0&quot;)</value>
      <webElementGuid>cd50bbf1-96b0-4f9c-8da2-bdaedb79afef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sex-0']</value>
      <webElementGuid>0380bc3f-5b20-41e7-8b20-30ed74f705b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[9]/input</value>
      <webElementGuid>76a458e0-a94a-4c8b-b183-56fc1532ffb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>e293354b-b836-442c-9c91-1d1874086fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sex-0' and @name = 'sex' and @type = 'radio']</value>
      <webElementGuid>6c4341d9-92cc-4ef8-946e-5033756b307e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
