<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Automation Tools_tool</name>
   <tag></tag>
   <elementGuidId>eec943b8-6224-4810-b6a6-97ad87d6e5a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tool-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tool-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1928b89-2d69-4214-be18-796440d0ce49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tool-2</value>
      <webElementGuid>1d55da71-594a-440a-9663-b0ac0b429ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tool</value>
      <webElementGuid>cbd4e6a0-6b58-4355-9d2a-64fb2a54c854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f5feeb4f-7b59-45af-bd21-00ba49c81a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Selenium Webdriver</value>
      <webElementGuid>427c4ffa-2dd2-4f2a-9770-6b6310794769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tool-2&quot;)</value>
      <webElementGuid>035c2532-1113-4b8f-8503-566bbe509cc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tool-2']</value>
      <webElementGuid>ef3652fd-3927-4ac6-a5e5-8c2b992687dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[22]/input[3]</value>
      <webElementGuid>a4105a7a-416a-41b2-a632-806d1905ee95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/input[3]</value>
      <webElementGuid>613763ce-bca2-4d4c-a486-8e77ac8d871d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tool-2' and @name = 'tool' and @type = 'checkbox']</value>
      <webElementGuid>38c47754-5292-499d-8ddf-98f414489f60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
